export const START_CALL = "START_CALL"
export const JOIN_CALL = "JOIN_CALL"
export const END_CALL = "END_CALL"
export const SET_LOCAL_STREAM = "SET_LOCAL_STREAM"
export const SET_REMOTE_STREAM = "SET_REMOTE_STREAM"
export const TOGGLE_SPEAKER = "TOGGLE_SPEAKER"
export const TOGGLE_MIC = "TOGGLE_MIC"
export const TOGGLE_VIDEO = "TOGGLE_VIDEO"
