import Head from 'next/head'
import NavBar from "../components/nav-bar"
import LinkButton from "../components/buttons/link-button";

const navigation = [
    {name: 'Product', href: '#'},
    {name: 'Features', href: '#'},
    {name: 'Marketplace', href: '#'},
    {name: 'Company', href: '#'},
]

export default function Home() {
    return (
        <div className={"relative w-full h-screen bg-gradient-to-b from-blue-600 to-indigo-400 overflow-hidden"}>
            <Head>
                <title>Disagreement</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="flex flex-col z-10 relative max-w-screen-xl h-full mx-auto overflow-hidden px-4 sm:px-6 lg:px-8">

                <NavBar/>

                <main
                    className="flex justify-center items-center flex-1 max-w-7xl">
                    <div className="lg:max-w-2xl lg:w-full sm:text-center lg:text-left">
                        <h1 className="text-4xl tracking-tight font-extrabold text-center text-white sm:text-5xl md:text-6xl">
                            Your place to squabble
                        </h1>
                        <p className="mt-8 sm:mt-12 text-base text-center text-white sm:text-lg md:text-xl">
                            Whether you’re part of a school club, gaming group, worldwide art community,
                            or just a handful of friends that want to spend time together,
                            Disagreement makes it easy to talk every day and hang out more often.
                        </p>
                        <div className="mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-center">
                            <LinkButton name={"Sign In"} url={"#"}/>
                            <LinkButton name={"Sign Up"} url={"#"} secondary/>
                        </div>
                    </div>
                </main>
                <footer className={"text-center text-white"}>
                    Created by Chidubem Ovbiebo
                </footer>
            </div>
            <img src="/foreground-left.svg" className="absolute bottom-0 -left-1/4" alt=""/>
            <img src="/7b01f72a2054561145b6dd04add417c0.svg" className="hidden absolute bottom-0 -right-1/4 xl:block" alt=""/>
        </div>
    )
}
